### ISSUE TITLE
[F]: remove gif and stickers button

### ISSUE THREAD

**Issue by ungiglio** [ungiglio/DiscordDiscordia#24]
### Feature Description
Remove the stickers and gif button to clean the bar from redundant elements (prioritizing the plugins elements)
![image](https://github.com/user-attachments/assets/8b75a78a-58c0-4a9b-8766-ae59f1dfa059)

### Problem and Solution

Too many buttons in the text area

### Alternatives Considered

Only sticker may be enough 

### Potential Impact

Low (Nice-to-have)

### Contribution

Yes, I can help implement this feature

### Final Checklist

- [X] I have reviewed my submission for clarity and completeness.

**Comment by ungiglio** [comment]
Possible fix:

```css
button:has(.giftIconButton_efde15,[d^=" M-6,-10 C-6,-10 6,-10 6,-10 C8.208999633789062"]){
    display: none
}
```
